# Generated by Django 2.2.2 on 2019-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebankingtype',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
