# Generated by Django 2.2.2 on 2019-07-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190717_2048'),
        ('payments', '0002_auto_20190718_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.Patient'),
            preserve_default=False,
        ),
    ]
