# Generated by Django 2.2.2 on 2019-08-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_historicalundefinedpaymentmethod_undefinedpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmobilebankingpayment',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmobilebankingpayment',
            name='mobile_banking_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.MobileBankingType'),
        ),
        migrations.AlterField(
            model_name='mobilebankingpayment',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mobilebankingpayment',
            name='mobile_banking_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.MobileBankingType'),
        ),
    ]
