# Generated by Django 2.2.2 on 2019-07-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebankingpayment',
            name='id',
        ),
        migrations.AddField(
            model_name='mobilebankingpayment',
            name='payment_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment'),
            preserve_default=False,
        ),
    ]
