# Generated by Django 2.2.2 on 2019-07-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, default='none.none@none', max_length=254)),
                ('uhid', models.IntegerField(blank=True, unique=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, default='none.none@none', max_length=254)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Gender')),
            ],
        ),
    ]
