# Generated by Django 2.2.2 on 2019-08-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='uhid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
