# Generated by Django 2.2.2 on 2019-08-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190819_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='date_added',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
