# Generated by Django 2.2.2 on 2019-07-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190717_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
