# Generated by Django 2.2.2 on 2019-07-22 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='Service. No further description provided', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(editable=False, max_length=10)),
                ('indicator', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Session Statuses',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_diagnosis', models.TextField(max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Patient')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.SessionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_cancelling', models.TextField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Session')),
            ],
        ),
    ]
