# Generated by Django 2.2.2 on 2019-08-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Service'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookings.SessionStatus'),
        ),
        migrations.AddField(
            model_name='historicalsessionstatus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.Doctor'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.Payment'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.Service'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.SessionStatus'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcancelledsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcancelledsession',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.Session'),
        ),
        migrations.AddField(
            model_name='cancelledsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Session'),
        ),
    ]
