# Generated by Django 2.2.2 on 2019-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='Service. No further description provided', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sessionstatus',
            options={'verbose_name_plural': 'Session Statuses'},
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookings.Service'),
            preserve_default=False,
        ),
    ]
