# Generated by Django 2.2.2 on 2019-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190807_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
