# Generated by Django 2.2.2 on 2019-08-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190818_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_date',
        ),
    ]
