# Generated by Django 2.2.2 on 2019-08-18 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20190818_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 8, 21, 6, 56, 24, 832366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 8, 21, 6, 56, 24, 832366, tzinfo=utc)),
        ),
    ]
