# Generated by Django 2.2.2 on 2019-08-18 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20190818_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 21)),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 8, 21)),
        ),
    ]
