# Generated by Django 2.2.2 on 2019-08-18 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20190818_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
