# Generated by Django 2.2.2 on 2019-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20190818_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='date_added',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
